language: python

python:
  - "2.7"
  - "3.6"

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE test_db;'

env:
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.7

install:
  - pip install -q Django==$DJANGO_VERSION

script:
  - python manage.py test
